version: '3'

services:
  json_server:
    image: python:3.8
    container_name: json_server
    working_dir: /app
    volumes:
      - ./json_server.py:/app/json_server.py
      - /tmp/enb_report.json:/tmp/enb_report.json
      - ./requirements.txt:/app/requirements.txt
    command: sh -c "pip install -r /app/requirements.txt && python /app/json_server.py"
    ports:
      - "5000:5000"

  json_exporter:
    image: prometheuscommunity/json-exporter:latest
    container_name: json_exporter
    ports:
      - "7979:7979"
    volumes:
      - /home/jin/monitoring/prometheus/config.yml:/config/config.yml
    command: --config.file=/config/config.yml

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
      - ./prometheus/logs:/logs
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana_monitor
    environment:
      - GF_SECURITY_ADMIN_USER=admin      # Grafana 기본 사용자 이름
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Grafana 기본 비밀번호
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/data:/var/lib/grafana
      - ./grafana/logs:/var/log/grafana
    ports:
      - "3000:3000"

