global:
  scrape_interval: 1s        # 1초마다 데이터 수집

scrape_configs:
  - job_name: 'json_exporter'
    scrape_interval: 1s
    metrics_path: '/probe'
    params:
      module: [json]
    static_configs:
      - targets: ['localhost:7979']

