global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'json_exporter'
    scrape_interval: 1s
    metrics_path: '/probe'
    params:
      module: [json]
    static_configs:
      - targets: ['json_exporter:7979']

